### ISSUE TITLE
A problem while loading model parameters.

### ISSUE THREAD

**Issue by invictuszhao** [wyqing20/PFRec#3]
When I load the existing pretrained model, the following error was reported: "RuntimeError: Error(s) in loading state_dict for FairModel4CIKM:
	Missing key(s) in state_dict: "i_embeddings.weight", "p_embeddings.weight", "prefix_gen.weight", "prefix_gen.bias", "side_embeddings.g_embeddings.weight", "side_embeddings.y_embeddings.weight", "side_embeddings.power_embeddings.weight", "encoder.p_embeddings.weight", "encoder.transformer_block.0.masked_attn_head.q_linear.weight", "encoder.transformer_block.0.masked_attn_head.q_linear.bias", "encoder.transformer_block.0.masked_attn_head.k_linear.weight", "encoder.transformer_block.0.masked_attn_head.k_linear.bias", "encoder.transformer_block.0.masked_attn_head.v_linear.weight", "encoder.transformer_block.0.masked_attn_head.v_linear.bias", "encoder.transformer_block.0.layer_norm1.weight", "encoder.transformer_block.0.layer_norm1.bias", "encoder.transformer_block.0.linear1.weight", "encoder.transformer_block.0.linear1.bias", "encoder.transformer_block.0.linear2.weight", "encoder.transformer_block.0.linear2.bias", "encoder.transformer_block.0.layer_norm2.weight", "encoder.transformer_block.0.layer_norm2.bias", "feature_gen.0.weight", "feature_gen.0.bias", "feature_gen.2.weight", "feature_gen.2.bias". 
	Unexpected key(s) in state_dict: "state_dict", "g_optimizer", "d_optimizer". "
If you have time, could you please help solve this problem? Thank you！

**Comment by invictuszhao** [comment]
The complete error message is as follows:
RuntimeError: Error(s) in loading state_dict for FairModel4CIKM:
	Unexpected key(s) in state_dict: "prefix_embedding.weight", "prefix_q_embedding.weight", "age_embedding.weight", "gender_embedding.weight", "occupation_embedding.weight", "prediction.0.weight", "prediction.0.bias", "prediction.2.weight", "prediction.2.bias", "c_loss_fun.weight", "classify_loss_fun.weight", "adapter1.0.weight", "adapter1.0.bias", "adapter1.1.weight", "adapter1.1.bias", "adapter1.3.weight", "adapter1.3.bias", "adapter2.0.weight", "adapter2.0.bias", "adapter2.1.weight", "adapter2.1.bias", "adapter2.3.weight", "adapter2.3.bias", "adapter.0.weight", "adapter.0.bias", "adapter.2.weight", "adapter.2.bias", "adapter.3.weight", "adapter.3.bias". 
	size mismatch for p_embeddings.weight: copying a param with shape torch.Size([21, 64]) from checkpoint, the shape in current model is torch.Size([101, 64]).
	size mismatch for encoder.p_embeddings.weight: copying a param with shape torch.Size([21, 64]) from checkpoint, the shape in current model is torch.Size([101, 64]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_fair.py", line 152, in <module>
    main()
  File "main_fair.py", line 73, in main
    model.actions_before_train()
  File "/data2/ZhaoMiaomiao1/PFRec-main/src/models/sequential/FairModel4CIKM.py", line 133, in actions_before_train
    self.load_model(self.pre_path)
  File "/data2/ZhaoMiaomiao1/PFRec-main/src/models/sequential/FairModel4CIKM.py", line 122, in load_model
    self.load_state_dict(torch.load(model_path)) #for only save model  state dict
  File "/data2/ZhaoMiaomiao1/miniconda3/envs/pytorch112/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FairModel4CIKM:
	Missing key(s) in state_dict: "i_embeddings.weight", "p_embeddings.weight", "prefix_gen.weight", "prefix_gen.bias", "side_embeddings.g_embeddings.weight", "side_embeddings.y_embeddings.weight", "side_embeddings.power_embeddings.weight", "encoder.p_embeddings.weight", "encoder.transformer_block.0.masked_attn_head.q_linear.weight", "encoder.transformer_block.0.masked_attn_head.q_linear.bias", "encoder.transformer_block.0.masked_attn_head.k_linear.weight", "encoder.transformer_block.0.masked_attn_head.k_linear.bias", "encoder.transformer_block.0.masked_attn_head.v_linear.weight", "encoder.transformer_block.0.masked_attn_head.v_linear.bias", "encoder.transformer_block.0.layer_norm1.weight", "encoder.transformer_block.0.layer_norm1.bias", "encoder.transformer_block.0.linear1.weight", "encoder.transformer_block.0.linear1.bias", "encoder.transformer_block.0.linear2.weight", "encoder.transformer_block.0.linear2.bias", "encoder.transformer_block.0.layer_norm2.weight", "encoder.transformer_block.0.layer_norm2.bias", "feature_gen.0.weight", "feature_gen.0.bias", "feature_gen.2.weight", "feature_gen.2.bias". 
	Unexpected key(s) in state_dict: "state_dict", "g_optimizer", "d_optimizer".

**Comment by wyqing20** [comment]
Hi,  It's probably your checkpoint that's causing the problem， as you can see " the Unexpected key(s) in state_dict: "state_dict", "g_optimizer", "d_optimizer"."   In my source code, I load the state_dict i.e., self.load_state_dict(torch. load(model_path)), so the checkpoint does not include the optimizer.  maybe you can use the code self.load_state_dict(torch. load(model_path)['state_dict']). But actually,  the srouce code will automatically save the checkpoint during the training stage.
